package messagecatalog

// MessageID .
type MessageID uint64

const sidx = 2000

const (
	// Default1 .
	Default1 MessageID = iota + sidx

	// Messages for GetStorageAdminInfo operation
	INFO_GET_STORAGEADMININFO_BEGIN
	INFO_GET_STORAGEADMININFO_END
	ERR_GET_STORAGEADMININFO_FAILED

	// Messages for GetVolumeQosAdminInfo operation
	INFO_GET_VOLUME_QOS_ADMIN_BEGIN
	INFO_GET_VOLUME_QOS_ADMIN_END
	ERR_GET_VOLUME_QOS_ADMIN_FAILED

	// Messages for SetVolumeQosAdminInfo operation
	INFO_SET_VOLUME_QOS_ADMIN_BEGIN
	INFO_SET_VOLUME_QOS_ADMIN_END
	ERR_SET_VOLUME_QOS_ADMIN_FAILED

	// VOLUMES
	INFO_GET_VOLUMES_BEGIN
	INFO_GET_VOLUMES_END
	ERR_GET_VOLUMES_FAILED

	INFO_GET_VOLUME_BY_ID_BEGIN
	INFO_GET_VOLUME_BY_ID_END
	ERR_GET_VOLUME_BY_ID_FAILED

	INFO_CREATE_VOLUMES_BEGIN
	INFO_CREATE_VOLUMES_END
	ERR_CREATE_VOLUMES_FAILED

	INFO_DELETE_VOLUME_BEGIN
	INFO_DELETE_VOLUME_END
	ERR_DELETE_VOLUME_FAILED

	INFO_EXPAND_VOLUME_BEGIN
	INFO_EXPAND_VOLUME_END
	ERR_EXPAND_VOLUME_FAILED

	INFO_UPDATE_VOLUME_NICKNAME_BEGIN
	INFO_UPDATE_VOLUME_NICKNAME_END
	ERR_UPDATE_VOLUME_NICKNAME_FAILED

	INFO_UPDATE_VOLUME_REDUCTION_BEGIN
	INFO_UPDATE_VOLUME_REDUCTION_END
	ERR_UPDATE_VOLUME_REDUCTION_FAILED

	INFO_GET_VOLUME_SERVER_CONNECTIONS_BEGIN
	INFO_GET_VOLUME_SERVER_CONNECTIONS_END
	ERR_GET_VOLUME_SERVER_CONNECTIONS_FAILED

	INFO_GET_VOLUME_SERVER_CONNECTION_BEGIN
	INFO_GET_VOLUME_SERVER_CONNECTION_END
	ERR_GET_VOLUME_SERVER_CONNECTION_FAILED

	INFO_ATTACH_VOLUME_SERVER_CONNECTION_BEGIN
	INFO_ATTACH_VOLUME_SERVER_CONNECTION_END
	ERR_ATTACH_VOLUME_SERVER_CONNECTION_FAILED

	INFO_DETACH_VOLUME_SERVER_CONNECTION_BEGIN
	INFO_DETACH_VOLUME_SERVER_CONNECTION_END
	ERR_DETACH_VOLUME_SERVER_CONNECTION_FAILED

	// Messages for SetVolumeQosAdminThreshold operation
	INFO_SET_VOLUME_QOS_ADMIN_THRESHOLD_BEGIN
	INFO_SET_VOLUME_QOS_ADMIN_THRESHOLD_END
	ERR_SET_VOLUME_QOS_ADMIN_THRESHOLD_FAILED

	// Messages for SetVolumeQosAdminAlertSetting operation
	INFO_SET_VOLUME_QOS_ADMIN_ALERT_BEGIN
	INFO_SET_VOLUME_QOS_ADMIN_ALERT_END
	ERR_SET_VOLUME_QOS_ADMIN_ALERT_FAILED

	INFO_GET_ISCSI_TARGETS_BEGIN
	INFO_GET_ISCSI_TARGETS_END
	ERR_GET_ISCSI_TARGETS_FAILED

	INFO_GET_ISCSI_TARGET_BY_PORT_BEGIN
	INFO_GET_ISCSI_TARGET_BY_PORT_END
	ERR_GET_ISCSI_TARGET_BY_PORT_FAILED

	INFO_CHANGE_ISCSI_TARGET_NAME_BEGIN
	INFO_CHANGE_ISCSI_TARGET_NAME_END
	ERR_CHANGE_ISCSI_TARGET_NAME_FAILED

	INFO_ADD_HOSTGROUPS_TO_SERVER_BEGIN
	INFO_ADD_HOSTGROUPS_TO_SERVER_END
	ERR_ADD_HOSTGROUPS_TO_SERVER_FAILED

	INFO_SYNC_HOSTGROUPS_WITH_SERVER_BEGIN
	INFO_SYNC_HOSTGROUPS_WITH_SERVER_END
	ERR_SYNC_HOSTGROUPS_WITH_SERVER_FAILED

	// Messages for GetAdminServers operation
	INFO_GET_SERVERS_BEGIN
	INFO_GET_SERVERS_END
	ERR_GET_SERVERS_FAILED

	// Messages for GetAdminServerInfo operation
	INFO_GET_SERVER_INFO_BEGIN
	INFO_GET_SERVER_INFO_END
	ERR_GET_SERVER_INFO_FAILED

	// Messages for CreateAdminServer operation
	INFO_CREATE_SERVER_BEGIN
	INFO_CREATE_SERVER_END
	ERR_CREATE_SERVER_FAILED

	// Messages for UpdateAdminServer operation
	INFO_UPDATE_SERVER_BEGIN
	INFO_UPDATE_SERVER_END
	ERR_UPDATE_SERVER_FAILED

	// Messages for DeleteAdminServer operation
	INFO_DELETE_SERVER_BEGIN
	INFO_DELETE_SERVER_END
	ERR_DELETE_SERVER_FAILED

	// Messages for SetAdminServerPath operation
	INFO_SET_SERVER_PATH_BEGIN
	INFO_SET_SERVER_PATH_END
	ERR_SET_SERVER_PATH_FAILED

	// Messages for DeleteAdminServerPath operation
	INFO_DELETE_SERVER_PATH_BEGIN
	INFO_DELETE_SERVER_PATH_END
	ERR_DELETE_SERVER_PATH_FAILED

	// Messages for GetAdminServerPath operation
	INFO_GET_SERVER_PATH_BEGIN
	INFO_GET_SERVER_PATH_END
	ERR_GET_SERVER_PATH_FAILED

	// PORTS
	INFO_GET_PORTS_BEGIN
	INFO_GET_PORTS_END
	ERR_GET_PORTS_FAILED

	INFO_GET_PORT_BY_ID_BEGIN
	INFO_GET_PORT_BY_ID_END
	ERR_GET_PORT_BY_ID_FAILED

	INFO_UPDATE_PORT_BEGIN
	INFO_UPDATE_PORT_END
	ERR_UPDATE_PORT_FAILED

	// SERVER HBAS
	INFO_GET_SERVER_HBAS_BEGIN
	INFO_GET_SERVER_HBAS_END
	ERR_GET_SERVER_HBAS_FAILED

	INFO_GET_SERVER_HBA_BEGIN
	INFO_GET_SERVER_HBA_END
	ERR_GET_SERVER_HBA_FAILED

	// POOLS
	INFO_GET_POOLS_BEGIN
	INFO_GET_POOLS_END
	ERR_GET_POOLS_FAILED

	INFO_GET_POOL_INFO_BEGIN
	INFO_GET_POOL_INFO_END
	ERR_GET_POOL_INFO_FAILED

	INFO_CREATE_POOL_BEGIN
	INFO_CREATE_POOL_END
	ERR_CREATE_POOL_FAILED

	INFO_UPDATE_POOL_BEGIN
	INFO_UPDATE_POOL_END
	ERR_UPDATE_POOL_FAILED

	INFO_DELETE_POOL_BEGIN
	INFO_DELETE_POOL_END
	ERR_DELETE_POOL_FAILED
)

var enumStrings = map[interface{}]string{
	Default1: "Default1",

	INFO_GET_STORAGEADMININFO_BEGIN: "INFO_GET_STORAGEADMININFO_BEGIN",
	INFO_GET_STORAGEADMININFO_END:   "INFO_GET_STORAGEADMININFO_END",
	ERR_GET_STORAGEADMININFO_FAILED: "ERR_GET_STORAGEADMININFO_FAILED",

	INFO_GET_VOLUME_QOS_ADMIN_BEGIN: "INFO_GET_VOLUME_QOS_ADMIN_BEGIN",
	INFO_GET_VOLUME_QOS_ADMIN_END:   "INFO_GET_VOLUME_QOS_ADMIN_END",
	ERR_GET_VOLUME_QOS_ADMIN_FAILED: "ERR_GET_VOLUME_QOS_ADMIN_FAILED",

	INFO_SET_VOLUME_QOS_ADMIN_BEGIN: "INFO_SET_VOLUME_QOS_ADMIN_BEGIN",
	INFO_SET_VOLUME_QOS_ADMIN_END:   "INFO_SET_VOLUME_QOS_ADMIN_END",
	ERR_SET_VOLUME_QOS_ADMIN_FAILED: "ERR_SET_VOLUME_QOS_ADMIN_FAILED",

	// VOLUMES
	INFO_GET_VOLUMES_BEGIN: "INFO_GET_VOLUMES_BEGIN",
	INFO_GET_VOLUMES_END:   "INFO_GET_VOLUMES_END",
	ERR_GET_VOLUMES_FAILED: "ERR_GET_VOLUMES_FAILED",

	INFO_GET_VOLUME_BY_ID_BEGIN: "INFO_GET_VOLUME_BY_ID_BEGIN",
	INFO_GET_VOLUME_BY_ID_END:   "INFO_GET_VOLUME_BY_ID_END",
	ERR_GET_VOLUME_BY_ID_FAILED: "ERR_GET_VOLUME_BY_ID_FAILED",

	INFO_CREATE_VOLUMES_BEGIN: "INFO_CREATE_VOLUMES_BEGIN",
	INFO_CREATE_VOLUMES_END:   "INFO_CREATE_VOLUMES_END",
	ERR_CREATE_VOLUMES_FAILED: "ERR_CREATE_VOLUMES_FAILED",

	INFO_DELETE_VOLUME_BEGIN: "INFO_DELETE_VOLUME_BEGIN",
	INFO_DELETE_VOLUME_END:   "INFO_DELETE_VOLUME_END",
	ERR_DELETE_VOLUME_FAILED: "ERR_DELETE_VOLUME_FAILED",

	INFO_EXPAND_VOLUME_BEGIN: "INFO_EXPAND_VOLUME_BEGIN",
	INFO_EXPAND_VOLUME_END:   "INFO_EXPAND_VOLUME_END",
	ERR_EXPAND_VOLUME_FAILED: "ERR_EXPAND_VOLUME_FAILED",

	INFO_UPDATE_VOLUME_NICKNAME_BEGIN: "INFO_UPDATE_VOLUME_NICKNAME_BEGIN",
	INFO_UPDATE_VOLUME_NICKNAME_END:   "INFO_UPDATE_VOLUME_NICKNAME_END",
	ERR_UPDATE_VOLUME_NICKNAME_FAILED: "ERR_UPDATE_VOLUME_NICKNAME_FAILED",

	INFO_UPDATE_VOLUME_REDUCTION_BEGIN: "INFO_UPDATE_VOLUME_REDUCTION_BEGIN",
	INFO_UPDATE_VOLUME_REDUCTION_END:   "INFO_UPDATE_VOLUME_REDUCTION_END",
	ERR_UPDATE_VOLUME_REDUCTION_FAILED: "ERR_UPDATE_VOLUME_REDUCTION_FAILED",

	INFO_GET_VOLUME_SERVER_CONNECTIONS_BEGIN: "INFO_GET_VOLUME_SERVER_CONNECTIONS_BEGIN",
	INFO_GET_VOLUME_SERVER_CONNECTIONS_END:   "INFO_GET_VOLUME_SERVER_CONNECTIONS_END",
	ERR_GET_VOLUME_SERVER_CONNECTIONS_FAILED: "ERR_GET_VOLUME_SERVER_CONNECTIONS_FAILED",

	INFO_GET_VOLUME_SERVER_CONNECTION_BEGIN: "INFO_GET_VOLUME_SERVER_CONNECTION_BEGIN",
	INFO_GET_VOLUME_SERVER_CONNECTION_END:   "INFO_GET_VOLUME_SERVER_CONNECTION_END",
	ERR_GET_VOLUME_SERVER_CONNECTION_FAILED: "ERR_GET_VOLUME_SERVER_CONNECTION_FAILED",

	INFO_ATTACH_VOLUME_SERVER_CONNECTION_BEGIN: "INFO_ATTACH_VOLUME_SERVER_CONNECTION_BEGIN",
	INFO_ATTACH_VOLUME_SERVER_CONNECTION_END:   "INFO_ATTACH_VOLUME_SERVER_CONNECTION_END",
	ERR_ATTACH_VOLUME_SERVER_CONNECTION_FAILED: "ERR_ATTACH_VOLUME_SERVER_CONNECTION_FAILED",

	INFO_DETACH_VOLUME_SERVER_CONNECTION_BEGIN: "INFO_DETACH_VOLUME_SERVER_CONNECTION_BEGIN",
	INFO_DETACH_VOLUME_SERVER_CONNECTION_END:   "INFO_DETACH_VOLUME_SERVER_CONNECTION_END",
	ERR_DETACH_VOLUME_SERVER_CONNECTION_FAILED: "ERR_DETACH_VOLUME_SERVER_CONNECTION_FAILED",

	INFO_SET_VOLUME_QOS_ADMIN_THRESHOLD_BEGIN: "INFO_SET_VOLUME_QOS_ADMIN_THRESHOLD_BEGIN",
	INFO_SET_VOLUME_QOS_ADMIN_THRESHOLD_END:   "INFO_SET_VOLUME_QOS_ADMIN_THRESHOLD_END",
	ERR_SET_VOLUME_QOS_ADMIN_THRESHOLD_FAILED: "ERR_SET_VOLUME_QOS_ADMIN_THRESHOLD_FAILED",

	INFO_SET_VOLUME_QOS_ADMIN_ALERT_BEGIN: "INFO_SET_VOLUME_QOS_ADMIN_ALERT_BEGIN",
	INFO_SET_VOLUME_QOS_ADMIN_ALERT_END:   "INFO_SET_VOLUME_QOS_ADMIN_ALERT_END",
	ERR_SET_VOLUME_QOS_ADMIN_ALERT_FAILED: "ERR_SET_VOLUME_QOS_ADMIN_ALERT_FAILED",

	INFO_GET_ISCSI_TARGETS_BEGIN: "INFO_GET_ISCSI_TARGETS_BEGIN",
	INFO_GET_ISCSI_TARGETS_END:   "INFO_GET_ISCSI_TARGETS_END",
	ERR_GET_ISCSI_TARGETS_FAILED: "ERR_GET_ISCSI_TARGETS_FAILED",

	INFO_GET_ISCSI_TARGET_BY_PORT_BEGIN: "INFO_GET_ISCSI_TARGET_BY_PORT_BEGIN",
	INFO_GET_ISCSI_TARGET_BY_PORT_END:   "INFO_GET_ISCSI_TARGET_BY_PORT_END",
	ERR_GET_ISCSI_TARGET_BY_PORT_FAILED: "ERR_GET_ISCSI_TARGET_BY_PORT_FAILED",

	INFO_CHANGE_ISCSI_TARGET_NAME_BEGIN: "INFO_CHANGE_ISCSI_TARGET_NAME_BEGIN",
	INFO_CHANGE_ISCSI_TARGET_NAME_END:   "INFO_CHANGE_ISCSI_TARGET_NAME_END",
	ERR_CHANGE_ISCSI_TARGET_NAME_FAILED: "ERR_CHANGE_ISCSI_TARGET_NAME_FAILED",

	INFO_ADD_HOSTGROUPS_TO_SERVER_BEGIN: "INFO_ADD_HOSTGROUPS_TO_SERVER_BEGIN",
	INFO_ADD_HOSTGROUPS_TO_SERVER_END:   "INFO_ADD_HOSTGROUPS_TO_SERVER_END",
	ERR_ADD_HOSTGROUPS_TO_SERVER_FAILED: "ERR_ADD_HOSTGROUPS_TO_SERVER_FAILED",

	INFO_SYNC_HOSTGROUPS_WITH_SERVER_BEGIN: "INFO_SYNC_HOSTGROUPS_WITH_SERVER_BEGIN",
	INFO_SYNC_HOSTGROUPS_WITH_SERVER_END:   "INFO_SYNC_HOSTGROUPS_WITH_SERVER_END",
	ERR_SYNC_HOSTGROUPS_WITH_SERVER_FAILED: "ERR_SYNC_HOSTGROUPS_WITH_SERVER_FAILED",

	INFO_GET_SERVERS_BEGIN: "INFO_GET_SERVERS_BEGIN",
	INFO_GET_SERVERS_END:   "INFO_GET_SERVERS_END",
	ERR_GET_SERVERS_FAILED: "ERR_GET_SERVERS_FAILED",

	INFO_GET_SERVER_INFO_BEGIN: "INFO_GET_SERVER_INFO_BEGIN",
	INFO_GET_SERVER_INFO_END:   "INFO_GET_SERVER_INFO_END",
	ERR_GET_SERVER_INFO_FAILED: "ERR_GET_SERVER_INFO_FAILED",

	INFO_CREATE_SERVER_BEGIN: "INFO_CREATE_SERVER_BEGIN",
	INFO_CREATE_SERVER_END:   "INFO_CREATE_SERVER_END",
	ERR_CREATE_SERVER_FAILED: "ERR_CREATE_SERVER_FAILED",

	INFO_UPDATE_SERVER_BEGIN: "INFO_UPDATE_SERVER_BEGIN",
	INFO_UPDATE_SERVER_END:   "INFO_UPDATE_SERVER_END",
	ERR_UPDATE_SERVER_FAILED: "ERR_UPDATE_SERVER_FAILED",

	INFO_DELETE_SERVER_BEGIN: "INFO_DELETE_SERVER_BEGIN",
	INFO_DELETE_SERVER_END:   "INFO_DELETE_SERVER_END",
	ERR_DELETE_SERVER_FAILED: "ERR_DELETE_SERVER_FAILED",
	INFO_GET_PORTS_BEGIN:     "INFO_GET_PORTS_BEGIN",
	INFO_GET_PORTS_END:       "INFO_GET_PORTS_END",
	ERR_GET_PORTS_FAILED:     "ERR_GET_PORTS_FAILED",

	INFO_GET_PORT_BY_ID_BEGIN: "INFO_GET_PORT_BY_ID_BEGIN",
	INFO_GET_PORT_BY_ID_END:   "INFO_GET_PORT_BY_ID_END",
	ERR_GET_PORT_BY_ID_FAILED: "ERR_GET_PORT_BY_ID_FAILED",

	INFO_UPDATE_PORT_BEGIN: "INFO_UPDATE_PORT_BEGIN",
	INFO_UPDATE_PORT_END:   "INFO_UPDATE_PORT_END",
	ERR_UPDATE_PORT_FAILED: "ERR_UPDATE_PORT_FAILED",

	// SERVER HBAS
	INFO_GET_SERVER_HBAS_BEGIN: "INFO_GET_SERVER_HBAS_BEGIN",
	INFO_GET_SERVER_HBAS_END:   "INFO_GET_SERVER_HBAS_END",
	ERR_GET_SERVER_HBAS_FAILED: "ERR_GET_SERVER_HBAS_FAILED",

	INFO_GET_SERVER_HBA_BEGIN: "INFO_GET_SERVER_HBA_BEGIN",
	INFO_GET_SERVER_HBA_END:   "INFO_GET_SERVER_HBA_END",
	ERR_GET_SERVER_HBA_FAILED: "ERR_GET_SERVER_HBA_FAILED",
}

func (s MessageID) String() string { return enumStrings[s] }

// GetEnumString .
func GetEnumString(m interface{}) string {
	if m, ok := m.(MessageID); ok {
		return m.String()
	}

	return "UNKNOWN"
}
