package messagecatalog

// MessageID .
type MessageID uint64

const sidx = 2000

const (
	// Default1 .
	Default1 MessageID = iota + sidx
	// STORAGE SYSTEM
	INFO_GET_STORAGE_SYSTEM_BEGIN
	INFO_GET_STORAGE_SYSTEM_END
	ERR_GET_STORAGE_SYSTEM_FAILED

	// VOLUME
	INFO_GET_LUN_BEGIN
	INFO_GET_LUN_END
	ERR_GET_LUN_FAILED
	ERR_GET_ALL_LUN_FAILED
	ERR_CREATE_LUN_FAILED
	INFO_CREATE_LUN_BEGIN
	INFO_CREATE_LUN_END
	ERR_EXPAND_LUN_FAILED
	INFO_EXPAND_LUN_BEGIN
	INFO_EXPAND_LUN_END
	ERR_DELETE_LUN_FAILED
	INFO_DELETE_LUN_BEGIN
	INFO_DELETE_LUN_END
	INFO_GET_LUN_RANGE_BEGIN
	INFO_GET_LUN_RANGE_END
	ERR_UPDATE_LUN_FAILED
	INFO_UPDATE_LUN_BEGIN
	INFO_UPDATE_LUN_END

	// HOSTGROUP
	INFO_GET_HOSTGROUP_BEGIN
	INFO_GET_HOSTGROUP_END
	ERR_GET_HOSTGROUP_FAILED
	INFO_GET_ALL_HOSTGROUP_BEGIN
	INFO_GET_ALL_HOSTGROUP_END
	ERR_GET_ALL_HOSTGROUP_FAILED
	INFO_CREATE_HOSTGROUP_BEGIN
	INFO_CREATE_HOSTGROUP_END
	ERR_CREATE_HOSTGROUP_FAILED
	ERR_ADD_LDEV_TO_HOSTGROUP_FAILED
	ERR_ADD_WWN_TO_HOSTGROUP_FAILED
	ERR_SET_NICKNAME_TO_WWN_FAILED
	INFO_DELETE_HOSTGROUP_BEGIN
	INFO_DELETE_HOSTGROUP_END
	ERR_DELETE_HOSTGROUP_FAILED
	INFO_SET_MODE_OPTION_HOSTGROUP_BEGIN
	INFO_SET_MODE_OPTION_HOSTGROUP_END
	ERR_SET_MODE_OPTION_HOSTGROUP_FAILED
	INFO_DELETE_WWN_BEGIN
	INFO_DELETE_WWN_END
	ERR_DELETE_WWN_FAILED
	INFO_SET_NICKNAME_HOSTGROUP_BEGIN
	INFO_SET_NICKNAME_HOSTGROUP_END
	INFO_ADD_WWN_TO_HOSTGROUP_BEGIN
	INFO_ADD_WWN_TO_HOSTGROUP_END
	INFO_REMOVE_LUN_HOSTGROUP_BEGIN
	INFO_REMOVE_LUN_HOSTGROUP_END
	ERR_REMOVE_LUN_HOSTGROUP_FAILED
	INFO_ADD_LDEV_TO_HOSTGROUP_BEGIN
	INFO_ADD_LDEV_TO_HOSTGROUP_END

	// ISCSI TARGET
	INFO_GET_ISCSITARGET_BEGIN
	INFO_GET_ISCSITARGET_END
	ERR_GET_ISCSITARGET_FAILED
	INFO_GET_ISCSITARGET_BY_PORTID_BEGIN
	INFO_GET_ISCSITARGET_BY_PORTID_END
	ERR_GET_ISCSITARGET_BY_PORTID_FAILED
	INFO_GET_ALL_ISCSITARGET_BEGIN
	INFO_GET_ALL_ISCSITARGET_END
	ERR_GET_ALL_ISCSITARGET_FAILED
	INFO_SET_MODE_OPTION_ISCSITARGET_BEGIN
	INFO_SET_MODE_OPTION_ISCSITARGET_END
	ERR_SET_MODE_OPTION_ISCSITARGET_FAILED
	INFO_CREATE_ISCSITARGET_BEGIN
	INFO_CREATE_ISCSITARGET_END
	ERR_CREATE_ISCSITARGET_FAILED
	INFO_ADD_LDEV_TO_ISCSITARGET_BEGIN
	INFO_ADD_LDEV_TO_ISCSITARGET_END
	ERR_ADD_LDEV_TO_ISCSITARGET_FAILED
	INFO_ADD_IQN_NAME_TO_ISCSITARGET_BEGIN
	INFO_ADD_IQN_NAME_TO_ISCSITARGET_END
	ERR_ADD_IQN_NAME_TO_ISCSITARGET_FAILED
	INFO_ADD_NICKNAME_TO_ISCSITARGET_BEGIN
	INFO_ADD_NICKNAME_TO_ISCSITARGET_END
	ERR_ADD_NICKNAME_TO_ISCSITARGET_FAILED
	INFO_DELETE_IQN_NAME_BEGIN
	INFO_DELETE_IQN_NAME_END
	ERR_DELETE_IQN_NAME_FAILED
	INFO_DELETE_ISCSITARGET_BEGIN
	INFO_DELETE_ISCSITARGET_END
	ERR_DELETE_ISCSITARGET_FAILED

	// ISCSI TARGET CHAP USER
	INFO_GET_ISCSITARGET_CHAPUSER_BEGIN
	INFO_GET_ISCSITARGET_CHAPUSER_END
	ERR_GET_ISCSITARGET_CHAPUSER_FAILED
	INFO_GET_ISCSITARGET_CHAPUSERS_BEGIN
	INFO_GET_ISCSITARGET_CHAPUSERS_END
	ERR_GET_ISCSITARGET_CHAPUSERS_FAILED
	INFO_CREATE_ISCSITARGET_CHAPUSER_BEGIN
	INFO_CREATE_ISCSITARGET_CHAPUSER_END
	ERR_CREATE_ISCSITARGET_CHAPUSER_FAILED
	INFO_SET_ISCSITARGET_CHAPUSERNAME_BEGIN
	INFO_SET_ISCSITARGET_CHAPUSERNAME_END
	ERR_SET_ISCSITARGET_CHAPUSERNAME_FAILED
	INFO_SET_ISCSITARGET_CHAPUSERSECRET_BEGIN
	INFO_SET_ISCSITARGET_CHAPUSERSECRET_END
	ERR_SET_ISCSITARGET_CHAPUSERSECRET_FAILED
	INFO_DELETE_ISCSITARGET_CHAPUSER_BEGIN
	INFO_DELETE_ISCSITARGET_CHAPUSER_END
	ERR_DELETE_ISCSITARGET_CHAPUSER_FAILED
	INFO_CHANGE_ISCSITARGET_CHAPUSER_BEGIN
	INFO_CHANGE_ISCSITARGET_CHAPUSER_END
	ERR_CHANGE_ISCSITARGET_CHAPUSER_FAILED

	// STORAGE PORTS
	INFO_GET_STORAGE_PORTS_BEGIN
	INFO_GET_STORAGE_PORTS_END
	ERR_GET_STORAGE_PORTS_FAILED
	INFO_GET_STORAGE_PORTS_PORTID_BEGIN
	INFO_GET_STORAGE_PORTS_PORTID_END
	ERR_GET_STORAGE_PORTS_PORTID_FAILED

	// DYNAMIC POOL
	INFO_GET_DYNAMIC_POOLS_BEGIN
	INFO_GET_DYNAMIC_POOLS_END
	ERR_GET_DYNAMIC_POOLS_FAILED
	INFO_GET_DYNAMIC_POOL_ID_BEGIN
	INFO_GET_DYNAMIC_POOL_ID_END
	ERR_GET_DYNAMIC_POOL_ID_FAILED

	// PARITY GROUP
	INFO_GET_PARITY_GROUP_BEGIN
	INFO_GET_PARITY_GROUP_END
	ERR_GET_PARITY_GROUP_FAILED

	// SNAPSHOT (THIN IMAGE PAIRS)
	INFO_GET_SNAPSHOTS_BEGIN
	INFO_GET_SNAPSHOTS_END
	ERR_GET_SNAPSHOTS_FAILED
	INFO_GET_SNAPSHOT_BEGIN
	INFO_GET_SNAPSHOT_END
	ERR_GET_SNAPSHOT_FAILED
	INFO_GET_SNAPSHOT_REPLICATIONS_BEGIN
	INFO_GET_SNAPSHOT_REPLICATIONS_END
	ERR_GET_SNAPSHOT_REPLICATIONS_FAILED
	INFO_CREATE_SNAPSHOT_BEGIN
	INFO_CREATE_SNAPSHOT_END
	ERR_CREATE_SNAPSHOT_FAILED
	INFO_SPLIT_SNAPSHOT_BEGIN
	INFO_SPLIT_SNAPSHOT_END
	ERR_SPLIT_SNAPSHOT_FAILED
	INFO_RESYNC_SNAPSHOT_BEGIN
	INFO_RESYNC_SNAPSHOT_END
	ERR_RESYNC_SNAPSHOT_FAILED
	INFO_RESTORE_SNAPSHOT_BEGIN
	INFO_RESTORE_SNAPSHOT_END
	ERR_RESTORE_SNAPSHOT_FAILED
	INFO_DELETE_SNAPSHOT_BEGIN
	INFO_DELETE_SNAPSHOT_END
	ERR_DELETE_SNAPSHOT_FAILED
	INFO_CLONE_SNAPSHOT_BEGIN
	INFO_CLONE_SNAPSHOT_END
	ERR_CLONE_SNAPSHOT_FAILED
	INFO_ASSIGN_SNAPSHOT_VOLUME_BEGIN
	INFO_ASSIGN_SNAPSHOT_VOLUME_END
	ERR_ASSIGN_SNAPSHOT_VOLUME_FAILED
	INFO_UNASSIGN_SNAPSHOT_VOLUME_BEGIN
	INFO_UNASSIGN_SNAPSHOT_VOLUME_END
	ERR_UNASSIGN_SNAPSHOT_VOLUME_FAILED
	INFO_SNAPSHOT_RETENTION_BEGIN
	INFO_SNAPSHOT_RETENTION_END
	ERR_SNAPSHOT_RETENTION_FAILED

	// SNAPSHOT GROUP
	INFO_GET_SNAPSHOT_GROUPS_BEGIN
	INFO_GET_SNAPSHOT_GROUPS_END
	ERR_GET_SNAPSHOT_GROUPS_FAILED
	INFO_GET_SNAPSHOT_GROUP_BEGIN
	INFO_GET_SNAPSHOT_GROUP_END
	ERR_GET_SNAPSHOT_GROUP_FAILED
	INFO_SPLIT_SNAPSHOT_GROUP_BEGIN
	INFO_SPLIT_SNAPSHOT_GROUP_END
	ERR_SPLIT_SNAPSHOT_GROUP_FAILED
	INFO_RESYNC_SNAPSHOT_GROUP_BEGIN
	INFO_RESYNC_SNAPSHOT_GROUP_END
	ERR_RESYNC_SNAPSHOT_GROUP_FAILED
	INFO_RESTORE_SNAPSHOT_GROUP_BEGIN
	INFO_RESTORE_SNAPSHOT_GROUP_END
	ERR_RESTORE_SNAPSHOT_GROUP_FAILED
	INFO_DELETE_SNAPSHOT_GROUP_BEGIN
	INFO_DELETE_SNAPSHOT_GROUP_END
	ERR_DELETE_SNAPSHOT_GROUP_FAILED
	INFO_CLONE_SNAPSHOT_GROUP_BEGIN
	INFO_CLONE_SNAPSHOT_GROUP_END
	ERR_CLONE_SNAPSHOT_GROUP_FAILED
	INFO_SNAPSHOT_GROUP_RETENTION_BEGIN
	INFO_SNAPSHOT_GROUP_RETENTION_END
	ERR_SNAPSHOT_GROUP_RETENTION_FAILED

	// SNAPSHOT TREE & GARBAGE DATA
	INFO_DELETE_SNAPSHOT_TREE_BEGIN
	INFO_DELETE_SNAPSHOT_TREE_END
	ERR_DELETE_SNAPSHOT_TREE_FAILED
	INFO_DELETE_GARBAGE_DATA_BEGIN
	INFO_DELETE_GARBAGE_DATA_END
	ERR_DELETE_GARBAGE_DATA_FAILED

	// Virtual Clone Parents
	INFO_GET_VCLONE_PARENTS_BEGIN = iota
	INFO_GET_VCLONE_PARENTS_END
	ERR_GET_VCLONE_PARENTS_FAILED

	// Snapshot Family
	INFO_GET_SNAPSHOT_FAMILY_BEGIN
	INFO_GET_SNAPSHOT_FAMILY_END
	ERR_GET_SNAPSHOT_FAMILY_FAILED

	// Snapshot VClone (Individual)
	INFO_CREATE_VCLONE_BEGIN
	INFO_CREATE_VCLONE_END
	ERR_CREATE_VCLONE_FAILED
	INFO_CONVERT_VCLONE_BEGIN
	INFO_CONVERT_VCLONE_END
	ERR_CONVERT_VCLONE_FAILED
	INFO_RESTORE_VCLONE_BEGIN
	INFO_RESTORE_VCLONE_END
	ERR_RESTORE_VCLONE_FAILED

	// Snapshot Group VClone
	INFO_CREATE_GROUP_VCLONE_BEGIN
	INFO_CREATE_GROUP_VCLONE_END
	ERR_CREATE_GROUP_VCLONE_FAILED
	INFO_CONVERT_GROUP_VCLONE_BEGIN
	INFO_CONVERT_GROUP_VCLONE_END
	ERR_CONVERT_GROUP_VCLONE_FAILED
	INFO_RESTORE_GROUP_VCLONE_BEGIN
	INFO_RESTORE_GROUP_VCLONE_END
	ERR_RESTORE_GROUP_VCLONE_FAILED
)

var enumStrings = map[interface{}]string{
	Default1: "Default1",
	// STORAGE SYSTEM
	INFO_GET_STORAGE_SYSTEM_BEGIN: "INFO_GET_STORAGE_SYSTEM_BEGIN",
	INFO_GET_STORAGE_SYSTEM_END:   "INFO_GET_STORAGE_SYSTEM_END",
	ERR_GET_STORAGE_SYSTEM_FAILED: "ERR_GET_STORAGE_SYSTEM_FAILED",

	// VOLUME
	INFO_GET_LUN_BEGIN:       "INFO_GET_LUN_BEGIN",
	INFO_GET_LUN_END:         "INFO_GET_LUN_END",
	ERR_GET_LUN_FAILED:       "ERR_GET_LUN_FAILED",
	ERR_GET_ALL_LUN_FAILED:   "ERR_GET_ALL_LUN_FAILED",
	ERR_CREATE_LUN_FAILED:    "ERR_CREATE_LUN_FAILED",
	INFO_CREATE_LUN_BEGIN:    "INFO_CREATE_LUN_BEGIN",
	INFO_CREATE_LUN_END:      "INFO_CREATE_LUN_END",
	ERR_EXPAND_LUN_FAILED:    "ERR_EXPAND_LUN_FAILED",
	INFO_EXPAND_LUN_BEGIN:    "INFO_EXPAND_LUN_BEGIN",
	INFO_EXPAND_LUN_END:      "INFO_EXPAND_LUN_END",
	ERR_DELETE_LUN_FAILED:    "ERR_DELETE_LUN_FAILED",
	INFO_DELETE_LUN_BEGIN:    "INFO_DELETE_LUN_BEGIN",
	INFO_DELETE_LUN_END:      "INFO_DELETE_LUN_END",
	INFO_GET_LUN_RANGE_BEGIN: "INFO_GET_LUN_RANGE_BEGIN",
	INFO_GET_LUN_RANGE_END:   "INFO_GET_LUN_RANGE_END",
	ERR_UPDATE_LUN_FAILED:    "ERR_UPDATE_LUN_FAILED",
	INFO_UPDATE_LUN_BEGIN:    "INFO_UPDATE_LUN_BEGIN",
	INFO_UPDATE_LUN_END:      "INFO_UPDATE_LUN_END",

	// HOSTGROUP
	INFO_GET_HOSTGROUP_BEGIN:             "INFO_GET_HOSTGROUP_BEGIN",
	INFO_GET_HOSTGROUP_END:               "INFO_GET_HOSTGROUP_END",
	ERR_GET_HOSTGROUP_FAILED:             "ERR_GET_HOSTGROUP_FAILED",
	INFO_GET_ALL_HOSTGROUP_BEGIN:         "INFO_GET_ALL_HOSTGROUP_BEGIN",
	INFO_GET_ALL_HOSTGROUP_END:           "INFO_GET_ALL_HOSTGROUP_END",
	ERR_GET_ALL_HOSTGROUP_FAILED:         "ERR_GET_ALL_HOSTGROUP_FAILED",
	INFO_CREATE_HOSTGROUP_BEGIN:          "INFO_CREATE_HOSTGROUP_BEGIN",
	INFO_CREATE_HOSTGROUP_END:            "INFO_CREATE_HOSTGROUP_END",
	ERR_CREATE_HOSTGROUP_FAILED:          "ERR_CREATE_HOSTGROUP_FAILED",
	ERR_ADD_LDEV_TO_HOSTGROUP_FAILED:     "ERR_ADD_LDEV_TO_HOSTGROUP_FAILED",
	ERR_ADD_WWN_TO_HOSTGROUP_FAILED:      "ERR_ADD_WWN_TO_HOSTGROUP_FAILED",
	ERR_SET_NICKNAME_TO_WWN_FAILED:       "ERR_SET_NICKNAME_TO_WWN_FAILED",
	INFO_DELETE_HOSTGROUP_BEGIN:          "INFO_DELETE_HOSTGROUP_BEGIN",
	INFO_DELETE_HOSTGROUP_END:            "INFO_DELETE_HOSTGROUP_END",
	ERR_DELETE_HOSTGROUP_FAILED:          "ERR_DELETE_HOSTGROUP_FAILED",
	INFO_SET_MODE_OPTION_HOSTGROUP_BEGIN: "INFO_SET_MODE_OPTION_HOSTGROUP_BEGIN",
	INFO_SET_MODE_OPTION_HOSTGROUP_END:   "INFO_SET_MODE_OPTION_HOSTGROUP_END",
	ERR_SET_MODE_OPTION_HOSTGROUP_FAILED: "ERR_SET_MODE_OPTION_HOSTGROUP_FAILED",
	INFO_DELETE_WWN_BEGIN:                "INFO_DELETE_WWN_BEGIN",
	INFO_DELETE_WWN_END:                  "INFO_DELETE_WWN_END",
	ERR_DELETE_WWN_FAILED:                "ERR_DELETE_WWN_FAILED",
	INFO_SET_NICKNAME_HOSTGROUP_BEGIN:    "INFO_SET_NICKNAME_HOSTGROUP_BEGIN",
	INFO_SET_NICKNAME_HOSTGROUP_END:      "INFO_SET_NICKNAME_HOSTGROUP_END",
	INFO_ADD_WWN_TO_HOSTGROUP_BEGIN:      "INFO_ADD_WWN_TO_HOSTGROUP_BEGIN",
	INFO_ADD_WWN_TO_HOSTGROUP_END:        "INFO_ADD_WWN_TO_HOSTGROUP_END",
	INFO_REMOVE_LUN_HOSTGROUP_BEGIN:      "INFO_REMOVE_LUN_HOSTGROUP_BEGIN",
	INFO_REMOVE_LUN_HOSTGROUP_END:        "INFO_REMOVE_LUN_HOSTGROUP_END",
	ERR_REMOVE_LUN_HOSTGROUP_FAILED:      "ERR_REMOVE_LUN_HOSTGROUP_FAILED",
	INFO_ADD_LDEV_TO_HOSTGROUP_BEGIN:     "INFO_ADD_LDEV_TO_HOSTGROUP_BEGIN",
	INFO_ADD_LDEV_TO_HOSTGROUP_END:       "INFO_ADD_LDEV_TO_HOSTGROUP_END",

	// ISCSI TARGET
	INFO_GET_ISCSITARGET_BEGIN:             "INFO_GET_ISCSITARGET_BEGIN",
	INFO_GET_ISCSITARGET_END:               "INFO_GET_ISCSITARGET_END",
	ERR_GET_ISCSITARGET_FAILED:             "ERR_GET_ISCSITARGET_FAILED",
	INFO_GET_ISCSITARGET_BY_PORTID_BEGIN:   "INFO_GET_ISCSITARGET_BY_PORTID_BEGIN",
	INFO_GET_ISCSITARGET_BY_PORTID_END:     "INFO_GET_ISCSITARGET_BY_PORTID_END",
	ERR_GET_ISCSITARGET_BY_PORTID_FAILED:   "ERR_GET_ISCSITARGET_BY_PORTID_FAILED",
	INFO_GET_ALL_ISCSITARGET_BEGIN:         "INFO_GET_ALL_ISCSITARGET_BEGIN",
	INFO_GET_ALL_ISCSITARGET_END:           "INFO_GET_ALL_ISCSITARGET_END",
	ERR_GET_ALL_ISCSITARGET_FAILED:         "ERR_GET_ALL_ISCSITARGET_FAILED",
	INFO_SET_MODE_OPTION_ISCSITARGET_BEGIN: "INFO_SET_MODE_OPTION_ISCSITARGET_BEGIN",
	INFO_SET_MODE_OPTION_ISCSITARGET_END:   "INFO_SET_MODE_OPTION_ISCSITARGET_END",
	ERR_SET_MODE_OPTION_ISCSITARGET_FAILED: "ERR_SET_MODE_OPTION_ISCSITARGET_FAILED",
	INFO_CREATE_ISCSITARGET_BEGIN:          "INFO_CREATE_ISCSITARGET_BEGIN",
	INFO_CREATE_ISCSITARGET_END:            "INFO_CREATE_ISCSITARGET_END",
	ERR_CREATE_ISCSITARGET_FAILED:          "ERR_CREATE_ISCSITARGET_FAILED",
	INFO_ADD_LDEV_TO_ISCSITARGET_BEGIN:     "INFO_ADD_LDEV_TO_ISCSITARGET_BEGIN",
	INFO_ADD_LDEV_TO_ISCSITARGET_END:       "INFO_ADD_LDEV_TO_ISCSITARGET_END",
	ERR_ADD_LDEV_TO_ISCSITARGET_FAILED:     "ERR_ADD_LDEV_TO_ISCSITARGET_FAILED",
	INFO_ADD_IQN_NAME_TO_ISCSITARGET_BEGIN: "INFO_ADD_IQN_NAME_TO_ISCSITARGET_BEGIN",
	INFO_ADD_IQN_NAME_TO_ISCSITARGET_END:   "INFO_ADD_IQN_NAME_TO_ISCSITARGET_END",
	ERR_ADD_IQN_NAME_TO_ISCSITARGET_FAILED: "ERR_ADD_IQN_NAME_TO_ISCSITARGET_FAILED",
	INFO_ADD_NICKNAME_TO_ISCSITARGET_BEGIN: "INFO_ADD_NICKNAME_TO_ISCSITARGET_BEGIN",
	INFO_ADD_NICKNAME_TO_ISCSITARGET_END:   "INFO_ADD_NICKNAME_TO_ISCSITARGET_END",
	ERR_ADD_NICKNAME_TO_ISCSITARGET_FAILED: "ERR_ADD_NICKNAME_TO_ISCSITARGET_FAILED",
	INFO_DELETE_IQN_NAME_BEGIN:             "INFO_DELETE_IQN_NAME_BEGIN",
	INFO_DELETE_IQN_NAME_END:               "INFO_DELETE_IQN_NAME_END",
	ERR_DELETE_IQN_NAME_FAILED:             "ERR_DELETE_IQN_NAME_FAILED",
	INFO_DELETE_ISCSITARGET_BEGIN:          "INFO_DELETE_ISCSITARGET_BEGIN",
	INFO_DELETE_ISCSITARGET_END:            "INFO_DELETE_ISCSITARGET_END",
	ERR_DELETE_ISCSITARGET_FAILED:          "ERR_DELETE_ISCSITARGET_FAILED",

	// ISCSI TARGET CHAP USERS
	INFO_GET_ISCSITARGET_CHAPUSER_BEGIN:       "INFO_GET_ISCSITARGET_CHAPUSER_BEGIN",
	INFO_GET_ISCSITARGET_CHAPUSER_END:         "INFO_GET_ISCSITARGET_CHAPUSER_END",
	ERR_GET_ISCSITARGET_CHAPUSER_FAILED:       "ERR_GET_ISCSITARGET_CHAPUSER_FAILED",
	INFO_GET_ISCSITARGET_CHAPUSERS_BEGIN:      "INFO_GET_ISCSITARGET_CHAPUSERS_BEGIN",
	INFO_GET_ISCSITARGET_CHAPUSERS_END:        "INFO_GET_ISCSITARGET_CHAPUSERS_END",
	ERR_GET_ISCSITARGET_CHAPUSERS_FAILED:      "ERR_GET_ISCSITARGET_CHAPUSERS_FAILED",
	INFO_CREATE_ISCSITARGET_CHAPUSER_BEGIN:    "INFO_CREATE_ISCSITARGET_CHAPUSER_BEGIN",
	INFO_CREATE_ISCSITARGET_CHAPUSER_END:      "INFO_CREATE_ISCSITARGET_CHAPUSER_END",
	ERR_CREATE_ISCSITARGET_CHAPUSER_FAILED:    "ERR_CREATE_ISCSITARGET_CHAPUSER_FAILED",
	INFO_SET_ISCSITARGET_CHAPUSERNAME_BEGIN:   "INFO_SET_ISCSITARGET_CHAPUSERNAME_BEGIN",
	INFO_SET_ISCSITARGET_CHAPUSERNAME_END:     "INFO_SET_ISCSITARGET_CHAPUSERNAME_END",
	ERR_SET_ISCSITARGET_CHAPUSERNAME_FAILED:   "ERR_SET_ISCSITARGET_CHAPUSERNAME_FAILED",
	INFO_SET_ISCSITARGET_CHAPUSERSECRET_BEGIN: "INFO_SET_ISCSITARGET_CHAPUSERSECRET_BEGIN",
	INFO_SET_ISCSITARGET_CHAPUSERSECRET_END:   "INFO_SET_ISCSITARGET_CHAPUSERSECRET_END",
	ERR_SET_ISCSITARGET_CHAPUSERSECRET_FAILED: "ERR_SET_ISCSITARGET_CHAPUSERSECRET_FAILED",
	INFO_DELETE_ISCSITARGET_CHAPUSER_BEGIN:    "INFO_DELETE_ISCSITARGET_CHAPUSER_BEGIN",
	INFO_DELETE_ISCSITARGET_CHAPUSER_END:      "INFO_DELETE_ISCSITARGET_CHAPUSER_END",
	ERR_DELETE_ISCSITARGET_CHAPUSER_FAILED:    "ERR_DELETE_ISCSITARGET_CHAPUSER_FAILED",
	INFO_CHANGE_ISCSITARGET_CHAPUSER_BEGIN:    "INFO_CHANGE_ISCSITARGET_CHAPUSER_BEGIN",
	INFO_CHANGE_ISCSITARGET_CHAPUSER_END:      "INFO_CHANGE_ISCSITARGET_CHAPUSER_END",
	ERR_CHANGE_ISCSITARGET_CHAPUSER_FAILED:    "ERR_CHANGE_ISCSITARGET_CHAPUSER_FAILED",

	// STORAGE PORTS
	INFO_GET_STORAGE_PORTS_BEGIN:        "INFO_GET_STORAGE_PORTS_BEGIN",
	INFO_GET_STORAGE_PORTS_END:          "INFO_GET_STORAGE_PORTS_END",
	ERR_GET_STORAGE_PORTS_FAILED:        "ERR_GET_STORAGE_PORTS_FAILED",
	INFO_GET_STORAGE_PORTS_PORTID_BEGIN: "INFO_GET_STORAGE_PORTS_PORTID_BEGIN",
	INFO_GET_STORAGE_PORTS_PORTID_END:   "INFO_GET_STORAGE_PORTS_PORTID_END",
	ERR_GET_STORAGE_PORTS_PORTID_FAILED: "ERR_GET_STORAGE_PORTS_PORTID_FAILED",

	// DYNAMIC POOL
	INFO_GET_DYNAMIC_POOLS_BEGIN:   "INFO_GET_DYNAMIC_POOLS_BEGIN",
	INFO_GET_DYNAMIC_POOLS_END:     "INFO_GET_DYNAMIC_POOLS_END",
	ERR_GET_DYNAMIC_POOLS_FAILED:   "ERR_GET_DYNAMIC_POOLS_FAILED",
	INFO_GET_DYNAMIC_POOL_ID_BEGIN: "INFO_GET_DYNAMIC_POOL_ID_BEGIN",
	INFO_GET_DYNAMIC_POOL_ID_END:   "INFO_GET_DYNAMIC_POOL_ID_END",
	ERR_GET_DYNAMIC_POOL_ID_FAILED: "ERR_GET_DYNAMIC_POOL_ID_FAILED",

	// PARITY GROUP
	INFO_GET_PARITY_GROUP_BEGIN: "INFO_GET_PARITY_GROUP_BEGIN",
	INFO_GET_PARITY_GROUP_END:   "INFO_GET_PARITY_GROUP_END",
	ERR_GET_PARITY_GROUP_FAILED: "ERR_GET_PARITY_GROUP_FAILED",

	// SNAPSHOT (THIN IMAGE PAIRS)
	INFO_GET_SNAPSHOTS_BEGIN:             "INFO_GET_SNAPSHOTS_BEGIN",
	INFO_GET_SNAPSHOTS_END:               "INFO_GET_SNAPSHOTS_END",
	ERR_GET_SNAPSHOTS_FAILED:             "ERR_GET_SNAPSHOTS_FAILED",
	INFO_GET_SNAPSHOT_BEGIN:              "INFO_GET_SNAPSHOT_BEGIN",
	INFO_GET_SNAPSHOT_END:                "INFO_GET_SNAPSHOT_END",
	ERR_GET_SNAPSHOT_FAILED:              "ERR_GET_SNAPSHOT_FAILED",
	INFO_GET_SNAPSHOT_REPLICATIONS_BEGIN: "INFO_GET_SNAPSHOT_REPLICATIONS_BEGIN",
	INFO_GET_SNAPSHOT_REPLICATIONS_END:   "INFO_GET_SNAPSHOT_REPLICATIONS_END",
	ERR_GET_SNAPSHOT_REPLICATIONS_FAILED: "ERR_GET_SNAPSHOT_REPLICATIONS_FAILED",
	INFO_CREATE_SNAPSHOT_BEGIN:           "INFO_CREATE_SNAPSHOT_BEGIN",
	INFO_CREATE_SNAPSHOT_END:             "INFO_CREATE_SNAPSHOT_END",
	ERR_CREATE_SNAPSHOT_FAILED:           "ERR_CREATE_SNAPSHOT_FAILED",
	INFO_SPLIT_SNAPSHOT_BEGIN:            "INFO_SPLIT_SNAPSHOT_BEGIN",
	INFO_SPLIT_SNAPSHOT_END:              "INFO_SPLIT_SNAPSHOT_END",
	ERR_SPLIT_SNAPSHOT_FAILED:            "ERR_SPLIT_SNAPSHOT_FAILED",
	INFO_RESYNC_SNAPSHOT_BEGIN:           "INFO_RESYNC_SNAPSHOT_BEGIN",
	INFO_RESYNC_SNAPSHOT_END:             "INFO_RESYNC_SNAPSHOT_END",
	ERR_RESYNC_SNAPSHOT_FAILED:           "ERR_RESYNC_SNAPSHOT_FAILED",
	INFO_RESTORE_SNAPSHOT_BEGIN:          "INFO_RESTORE_SNAPSHOT_BEGIN",
	INFO_RESTORE_SNAPSHOT_END:            "INFO_RESTORE_SNAPSHOT_END",
	ERR_RESTORE_SNAPSHOT_FAILED:          "ERR_RESTORE_SNAPSHOT_FAILED",
	INFO_DELETE_SNAPSHOT_BEGIN:           "INFO_DELETE_SNAPSHOT_BEGIN",
	INFO_DELETE_SNAPSHOT_END:             "INFO_DELETE_SNAPSHOT_END",
	ERR_DELETE_SNAPSHOT_FAILED:           "ERR_DELETE_SNAPSHOT_FAILED",
	INFO_CLONE_SNAPSHOT_BEGIN:            "INFO_CLONE_SNAPSHOT_BEGIN",
	INFO_CLONE_SNAPSHOT_END:              "INFO_CLONE_SNAPSHOT_END",
	ERR_CLONE_SNAPSHOT_FAILED:            "ERR_CLONE_SNAPSHOT_FAILED",
	INFO_ASSIGN_SNAPSHOT_VOLUME_BEGIN:    "INFO_ASSIGN_SNAPSHOT_VOLUME_BEGIN",
	INFO_ASSIGN_SNAPSHOT_VOLUME_END:      "INFO_ASSIGN_SNAPSHOT_VOLUME_END",
	ERR_ASSIGN_SNAPSHOT_VOLUME_FAILED:    "ERR_ASSIGN_SNAPSHOT_VOLUME_FAILED",
	INFO_UNASSIGN_SNAPSHOT_VOLUME_BEGIN:  "INFO_UNASSIGN_SNAPSHOT_VOLUME_BEGIN",
	INFO_UNASSIGN_SNAPSHOT_VOLUME_END:    "INFO_UNASSIGN_SNAPSHOT_VOLUME_END",
	ERR_UNASSIGN_SNAPSHOT_VOLUME_FAILED:  "ERR_UNASSIGN_SNAPSHOT_VOLUME_FAILED",
	INFO_SNAPSHOT_RETENTION_BEGIN:        "INFO_SNAPSHOT_RETENTION_BEGIN",
	INFO_SNAPSHOT_RETENTION_END:          "INFO_SNAPSHOT_RETENTION_END",
	ERR_SNAPSHOT_RETENTION_FAILED:        "ERR_SNAPSHOT_RETENTION_FAILED",

	// SNAPSHOT GROUP
	INFO_GET_SNAPSHOT_GROUPS_BEGIN: "INFO_GET_SNAPSHOT_GROUPS_BEGIN",
	INFO_GET_SNAPSHOT_GROUPS_END:   "INFO_GET_SNAPSHOT_GROUPS_END",
	ERR_GET_SNAPSHOT_GROUPS_FAILED: "ERR_GET_SNAPSHOT_GROUPS_FAILED",

	INFO_GET_SNAPSHOT_GROUP_BEGIN: "INFO_GET_SNAPSHOT_GROUP_BEGIN",
	INFO_GET_SNAPSHOT_GROUP_END:   "INFO_GET_SNAPSHOT_GROUP_END",
	ERR_GET_SNAPSHOT_GROUP_FAILED: "ERR_GET_SNAPSHOT_GROUP_FAILED",

	INFO_SPLIT_SNAPSHOT_GROUP_BEGIN: "INFO_SPLIT_SNAPSHOT_GROUP_BEGIN",
	INFO_SPLIT_SNAPSHOT_GROUP_END:   "INFO_SPLIT_SNAPSHOT_GROUP_END",
	ERR_SPLIT_SNAPSHOT_GROUP_FAILED: "ERR_SPLIT_SNAPSHOT_GROUP_FAILED",

	INFO_RESYNC_SNAPSHOT_GROUP_BEGIN: "INFO_RESYNC_SNAPSHOT_GROUP_BEGIN",
	INFO_RESYNC_SNAPSHOT_GROUP_END:   "INFO_RESYNC_SNAPSHOT_GROUP_END",
	ERR_RESYNC_SNAPSHOT_GROUP_FAILED: "ERR_RESYNC_SNAPSHOT_GROUP_FAILED",

	INFO_RESTORE_SNAPSHOT_GROUP_BEGIN: "INFO_RESTORE_SNAPSHOT_GROUP_BEGIN",
	INFO_RESTORE_SNAPSHOT_GROUP_END:   "INFO_RESTORE_SNAPSHOT_GROUP_END",
	ERR_RESTORE_SNAPSHOT_GROUP_FAILED: "ERR_RESTORE_SNAPSHOT_GROUP_FAILED",

	INFO_DELETE_SNAPSHOT_GROUP_BEGIN: "INFO_DELETE_SNAPSHOT_GROUP_BEGIN",
	INFO_DELETE_SNAPSHOT_GROUP_END:   "INFO_DELETE_SNAPSHOT_GROUP_END",
	ERR_DELETE_SNAPSHOT_GROUP_FAILED: "ERR_DELETE_SNAPSHOT_GROUP_FAILED",

	INFO_CLONE_SNAPSHOT_GROUP_BEGIN: "INFO_CLONE_SNAPSHOT_GROUP_BEGIN",
	INFO_CLONE_SNAPSHOT_GROUP_END:   "INFO_CLONE_SNAPSHOT_GROUP_END",
	ERR_CLONE_SNAPSHOT_GROUP_FAILED: "ERR_CLONE_SNAPSHOT_GROUP_FAILED",

	INFO_SNAPSHOT_GROUP_RETENTION_BEGIN: "INFO_SNAPSHOT_GROUP_RETENTION_BEGIN",
	INFO_SNAPSHOT_GROUP_RETENTION_END:   "INFO_SNAPSHOT_GROUP_RETENTION_END",
	ERR_SNAPSHOT_GROUP_RETENTION_FAILED: "ERR_SNAPSHOT_GROUP_RETENTION_FAILED",

	// Virtual Clone Parent Volumes
	INFO_GET_VCLONE_PARENTS_BEGIN: "INFO_GET_VCLONE_PARENTS_BEGIN",
	INFO_GET_VCLONE_PARENTS_END:   "INFO_GET_VCLONE_PARENTS_END",
	ERR_GET_VCLONE_PARENTS_FAILED: "ERR_GET_VCLONE_PARENTS_FAILED",

	// Snapshot Family
	INFO_GET_SNAPSHOT_FAMILY_BEGIN: "INFO_GET_SNAPSHOT_FAMILY_BEGIN",
	INFO_GET_SNAPSHOT_FAMILY_END:   "INFO_GET_SNAPSHOT_FAMILY_END",
	ERR_GET_SNAPSHOT_FAMILY_FAILED: "ERR_GET_SNAPSHOT_FAMILY_FAILED",

	// Snapshot VClone (Individual)
	INFO_CREATE_VCLONE_BEGIN: "INFO_CREATE_VCLONE_BEGIN",
	INFO_CREATE_VCLONE_END:   "INFO_CREATE_VCLONE_END",
	ERR_CREATE_VCLONE_FAILED: "ERR_CREATE_VCLONE_FAILED",

	INFO_CONVERT_VCLONE_BEGIN: "INFO_CONVERT_VCLONE_BEGIN",
	INFO_CONVERT_VCLONE_END:   "INFO_CONVERT_VCLONE_END",
	ERR_CONVERT_VCLONE_FAILED: "ERR_CONVERT_VCLONE_FAILED",

	INFO_RESTORE_VCLONE_BEGIN: "INFO_RESTORE_VCLONE_BEGIN",
	INFO_RESTORE_VCLONE_END:   "INFO_RESTORE_VCLONE_END",
	ERR_RESTORE_VCLONE_FAILED: "ERR_RESTORE_VCLONE_FAILED",

	// Snapshot Group VClone
	INFO_CREATE_GROUP_VCLONE_BEGIN: "INFO_CREATE_GROUP_VCLONE_BEGIN",
	INFO_CREATE_GROUP_VCLONE_END:   "INFO_CREATE_GROUP_VCLONE_END",
	ERR_CREATE_GROUP_VCLONE_FAILED: "ERR_CREATE_GROUP_VCLONE_FAILED",

	INFO_CONVERT_GROUP_VCLONE_BEGIN: "INFO_CONVERT_GROUP_VCLONE_BEGIN",
	INFO_CONVERT_GROUP_VCLONE_END:   "INFO_CONVERT_GROUP_VCLONE_END",
	ERR_CONVERT_GROUP_VCLONE_FAILED: "ERR_CONVERT_GROUP_VCLONE_FAILED",

	INFO_RESTORE_GROUP_VCLONE_BEGIN: "INFO_RESTORE_GROUP_VCLONE_BEGIN",
	INFO_RESTORE_GROUP_VCLONE_END:   "INFO_RESTORE_GROUP_VCLONE_END",
	ERR_RESTORE_GROUP_VCLONE_FAILED: "ERR_RESTORE_GROUP_VCLONE_FAILED",
}

func (s MessageID) String() string { return enumStrings[s] }

// GetEnumString .
func GetEnumString(m interface{}) string {
	if m, ok := m.(MessageID); ok {
		return m.String()
	}

	return "UNKNOWN"
}
