package messagecatalog

// MessageID .
type MessageID uint64

const sidx = 2000

const (
	// Default1 .
	Default1 MessageID = iota + sidx
	INFO_GET_STORAGE_SYSTEM_BEGIN
	INFO_GET_STORAGE_SYSTEM_END
	ERR_GET_STORAGE_SYSTEM_FAILED

	INFO_GET_INFRA_HOSTGROUPS_BEGIN
	ERR_GET_INFRA_HOSTGROUPS_FAILED
	INFO_GET_INFRA_HOSTGROUPS_END

	INFO_GET_INFRA_HOSTGROUP_BEGIN
	ERR_GET_INFRA_HOSTGROUP_FAILED
	INFO_GET_INFRA_HOSTGROUP_END

	INFO_GET_INFRA_ISCSI_TARGETS_BEGIN
	ERR_GET_INFRA_ISCSI_TARGETS_FAILED
	INFO_GET_INFRA_ISCSI_TARGETS_END

	INFO_GET_INFRA_ISCSI_TARGET_BEGIN
	ERR_GET_INFRA_ISCSI_TARGET_FAILED
	INFO_GET_INFRA_ISCSI_TARGET_END

	// Volume management

	INFO_GET_INFRA_GET_ALL_VOLUMES_BEGIN
	ERR_GET_INFRA_GET_ALL_VOLUMES_FAILED
	INFO_GET_INFRA_GET_ALL_VOLUMES_END

	INFO_GET_INFRA_GET_VOLUME_BEGIN
	ERR_GET_INFRA_GET_VOLUME_FAILED
	INFO_GET_INFRA_GET_VOLUME_END

	INFO_GET_INFRA_CREATE_VOLUME_BEGIN
	ERR_GET_INFRA_CREATE_VOLUME_FAILED
	INFO_GET_INFRA_CREATE_VOLUME_END

	INFO_GET_INFRA_UPDATE_VOLUME_BEGIN
	ERR_GET_INFRA_UPDATE_VOLUME_FAILED
	INFO_GET_INFRA_UPDATE_VOLUME_END

	INFO_GET_INFRA_DELETE_VOLUME_BEGIN
	ERR_GET_INFRA_DELETE_VOLUME_FAILED
	INFO_GET_INFRA_DELETE_VOLUME_END
)

var enumStrings = map[interface{}]string{
	Default1: "Default1",
	// STORAGE SYSTEM
	INFO_GET_STORAGE_SYSTEM_BEGIN: "INFO_GET_STORAGE_SYSTEM_BEGIN",
	INFO_GET_STORAGE_SYSTEM_END:   "INFO_GET_STORAGE_SYSTEM_END",
	ERR_GET_STORAGE_SYSTEM_FAILED: "ERR_GET_STORAGE_SYSTEM_FAILED",

	// HOST GROUP
	INFO_GET_INFRA_HOSTGROUPS_BEGIN: "INFO_GET_INFRA_HOSTGROUPS_BEGIN",
	ERR_GET_INFRA_HOSTGROUPS_FAILED: "ERR_GET_INFRA_HOSTGROUPS_FAILED",
	INFO_GET_INFRA_HOSTGROUPS_END:   "INFO_GET_INFRA_HOSTGROUPS_END",

	INFO_GET_INFRA_HOSTGROUP_BEGIN: "INFO_GET_INFRA_HOSTGROUP_BEGIN",
	ERR_GET_INFRA_HOSTGROUP_FAILED: "ERR_GET_INFRA_HOSTGROUP_FAILED",
	INFO_GET_INFRA_HOSTGROUP_END:   "INFO_GET_INFRA_HOSTGROUP_END",

	// ISCSI TARGET

	INFO_GET_INFRA_ISCSI_TARGETS_BEGIN: "INFO_GET_INFRA_ISCSI_TARGETS_BEGIN",
	ERR_GET_INFRA_ISCSI_TARGETS_FAILED: "ERR_GET_INFRA_ISCSI_TARGETS_FAILED",
	INFO_GET_INFRA_ISCSI_TARGETS_END:   "INFO_GET_INFRA_ISCSI_TARGETS_END",

	INFO_GET_INFRA_ISCSI_TARGET_BEGIN: "INFO_GET_INFRA_ISCSI_TARGET_BEGIN",
	ERR_GET_INFRA_ISCSI_TARGET_FAILED: "ERR_GET_INFRA_ISCSI_TARGET_FAILED",
	INFO_GET_INFRA_ISCSI_TARGET_END:   "INFO_GET_INFRA_ISCSI_TARGET_END",


	// Volume management

	INFO_GET_INFRA_GET_ALL_VOLUMES_BEGIN: "INFO_GET_INFRA_GET_ALL_VOLUMES_BEGIN",
	ERR_GET_INFRA_GET_ALL_VOLUMES_FAILED: "ERR_GET_INFRA_GET_ALL_VOLUMES_FAILED",
	INFO_GET_INFRA_GET_ALL_VOLUMES_END:   "INFO_GET_INFRA_GET_ALL_VOLUMES_END",
	INFO_GET_INFRA_GET_VOLUME_BEGIN:      "INFO_GET_INFRA_GET_VOLUME_BEGIN",
	ERR_GET_INFRA_GET_VOLUME_FAILED:      "ERR_GET_INFRA_GET_VOLUME_FAILED",
	INFO_GET_INFRA_GET_VOLUME_END:        "INFO_GET_INFRA_GET_VOLUME_END",

	INFO_GET_INFRA_CREATE_VOLUME_BEGIN: "INFO_GET_INFRA_CREATE_VOLUME_BEGIN",
	ERR_GET_INFRA_CREATE_VOLUME_FAILED: "ERR_GET_INFRA_CREATE_VOLUME_FAILED",
	INFO_GET_INFRA_CREATE_VOLUME_END:   "INFO_GET_INFRA_CREATE_VOLUME_END",

	INFO_GET_INFRA_UPDATE_VOLUME_BEGIN: "INFO_GET_INFRA_UPDATE_VOLUME_BEGIN",
	ERR_GET_INFRA_UPDATE_VOLUME_FAILED: "ERR_GET_INFRA_UPDATE_VOLUME_FAILED",
	INFO_GET_INFRA_UPDATE_VOLUME_END:   "INFO_GET_INFRA_UPDATE_VOLUME_END",

	INFO_GET_INFRA_DELETE_VOLUME_BEGIN: "INFO_GET_INFRA_DELETE_VOLUME_BEGIN",
	ERR_GET_INFRA_DELETE_VOLUME_FAILED: "ERR_GET_INFRA_DELETE_VOLUME_FAILED",
	INFO_GET_INFRA_DELETE_VOLUME_END:   "INFO_GET_INFRA_DELETE_VOLUME_END",
}
